markdown:         kramdown
highlighter:      pygments
permalink:        /:categories/:year/:month/:day/:title/

title:            "atleeon"
url:              http://atleeon.com
feed:             /feed.xml
author:
    name:         leeon
    twitter:      twitter.com/atleeon
    key:          atleeon
description:      "leeon，腾讯后台工程师，独立开发者，喜欢摄影、设计和读书。"
copyright:        "CopryRight Leeon 2014"
headdesc:         "leeon，腾讯后台工程师，独立开发者，喜欢摄影、设计和读书。"
headkeys:         "李阳,博客,设计,摄影,开发,Yoiware,WI输入法"
footdesc:         "Write 李阳 & Theme Guojing"
debug:            false